on:
  push:
    branches:
    - main
    - release/*
    
on:
  pull_request:
    branches:
    - main
  workflow_dispatch:
  
  jobs:
  my_job:
    name: deploy to staging
    runs-on: ubuntu-18.04
    
- name: Setup Node
  uses: actions/setup-node@v1
  with:
    node-version: '10.x'
    
- name: Install Dependencies
  run: npm install
